apiVersion:  v1
kind:  ReplicationController

metadata: 
  name:  myweb-rc

spec:
  replicas:  7
  selector:
    env:  production

  template:
    metadata:
      name:  myweb-pod2
      labels:  
        country: US
        env:  production    
    spec:
      containers:
      -  name:  myweb-con
         image:  httpd


